### ISSUE TITLE
Any reason to stick to Californium 1.0.6 instead of a 2.0.0-2.4.1 release?

### ISSUE THREAD

**Issue by boaks** [siemens/LightweightCmpRa#1]
I currently try to find out, how users decide to take which version of Californium in order to

- improve that decision
- improve newer Californium versions, if there are serious reasons to chose a older one.

So, have there been any serious reasons not to use one of the 2. releases of Californium?

**Comment by DDvO** [comment]
Thanks @boaks  for your comment.

@Akretsch should be able to answer this issue, but he likely will not be available before Tuesday...

**Comment by boaks** [comment]
Thanks, feedback will always be welcome, even after next week :-).

**Comment by Akretsch** [comment]
Hallo Achim,

I re-used the CoAP driver from an older project. So I stuck to 1.0.6. But its now fixed. Thanks for the tip!

**Comment by boaks** [comment]
Thanks for the answer.
