### ISSUE TITLE
`UpstreamInterface` and  `MessageInterface` config object: clarify choice taken

### ISSUE THREAD

**Issue by DDvO** [siemens/LightweightCmpRa#21]
For 
```
|0..n| [`HttpClient` object](#the-httpclient-object) |
|0..n| [`HttpsClient` object](#the-httpsclient-object) |
|0..n| [`CoapClient` object](#the-coapclient-object) |
|0..n| [`OfflineFileClient` object](#the-offlinefileclient-object) |
```
it should be defined which of them is chosen if, e.g., both `HttpClient` and `HttpsClient` (with no or with same `certProfile)` are given.

**Comment by Akretsch** [comment]
As explained before always the first matching entry in the array is used.

**Comment by DDvO** [comment]
Yes, this is what I found and somewhat suspected,
but the matching mechanism so far is described only for the RA component, not for the client.
Moreover, for both the use in the RA and the client, the situation here is special because the matching is not only within each of the lists of `HttpClient` , `HttpsClient`, `CoapClient`, and `OfflineFileClient`, but even across these lists!

For both the RA and the client you may write, e.g.,

The choice of the transport layer for a given message to be sent is done as follows.
If the message does not contain a `certProfile`, select the first element of the `HttpClient` , `HttpsClient`, `CoapClient`, or `OfflineFileClient` array that is specified first.
Otherwise select the first matching element in the order of all `HttpClient` , `HttpsClient`, `CoapClient`, or `OfflineFileClient` array elements specified, where 'matching' means that the element either has no **certProfile** restriction or the given string equals the `certProfile` string given in the message.

**Comment by Akretsch** [comment]
handled internally
